version: 2
updates:
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Europe/Zurich
  open-pull-requests-limit: 5
  groups:
    phpcs-stack:
      patterns:
      - squizlabs/php_codesniffer
      - wp-coding-standards/wpcs
      - phpcompatibility/*
      - dealerdirect/phpcodesniffer-composer-installer
      - phpcsstandards/*
  labels:
  - dependencies
  - php
  commit-message:
    prefix: chore(deps)
    prefix-development: chore(deps-dev)
    include: scope
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Europe/Zurich
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - github-actions
  commit-message:
    prefix: ci(deps)
    include: scope
